-- ============================================================================
-- CMAP 1815: Introduction to Modern SQL
-- Unit 4: Summarization, Aggregation & Pivoting
-- In-Class Paired Coding Challenges
-- ============================================================================

-- ----------------------------------------------------------------------------
-- CHALLENGE 1: Departmental Salary Audit (Session 1)
-- Scenario: The Chief Financial Officer wants an executive summary of payroll
-- across all departments.
-- Task:
-- 1. Project department name, total headcount, average salary (rounded to 2
--    decimal places), minimum salary, and maximum salary.
-- 2. Sort by average salary in descending order.
-- ----------------------------------------------------------------------------

-- Write your solution below:
SELECT 
    department,
    COUNT(*) AS total_headcount,
    ROUND(AVG(salary), 2) AS avg_salary,
    MIN(salary) AS min_salary,
    MAX(salary) AS max_salary
FROM employees
GROUP BY department
ORDER BY avg_salary DESC;


-- ----------------------------------------------------------------------------
-- CHALLENGE 2: Inventory Valuation by Category (Session 1)
-- Scenario: The warehouse manager needs an inventory health report.
-- Task:
-- 1. From the products table, group by category.
-- 2. Calculate:
--    - total_items: Total number of distinct products in the category.
--    - total_units_in_stock: Sum of stock_quantity.
--    - total_inventory_cost: Sum of (stock_quantity * wholesale_cost).
--    - potential_retail_revenue: Sum of (stock_quantity * retail_price).
-- 3. Round all monetary calculations to 2 decimal places.
-- 4. Filter for only active products (is_discontinued = FALSE).
-- 5. Sort by total_inventory_cost descending.
-- ----------------------------------------------------------------------------

-- Write your solution below:
SELECT 
    category,
    COUNT(*) AS total_items,
    SUM(stock_quantity) AS total_units_in_stock,
    ROUND(SUM(stock_quantity * wholesale_cost), 2) AS total_inventory_cost,
    ROUND(SUM(stock_quantity * retail_price), 2) AS potential_retail_revenue
FROM products
WHERE is_discontinued = FALSE
GROUP BY category
ORDER BY total_inventory_cost DESC;


-- ----------------------------------------------------------------------------
-- CHALLENGE 3: High-Performing Department Filter with HAVING (Session 2)
-- Scenario: HR wants to identify substantial departments with high average pay.
-- Task:
-- 1. From employees, group by department.
-- 2. Calculate active_staff_count and avg_active_salary.
-- 3. Filter using WHERE for is_active = TRUE.
-- 4. Filter using HAVING for departments with at least 3 active staff AND an
--    average salary greater than $65,000.
-- 5. Order by avg_active_salary descending.
-- ----------------------------------------------------------------------------

-- Write your solution below:
SELECT 
    department,
    COUNT(*) AS active_staff_count,
    ROUND(AVG(salary), 2) AS avg_active_salary
FROM employees
WHERE is_active = TRUE
GROUP BY department
HAVING COUNT(*) >= 3 AND AVG(salary) > 65000
ORDER BY avg_active_salary DESC;


-- ----------------------------------------------------------------------------
-- CHALLENGE 4: Set Operation Reconciliation (Session 2)
-- Scenario: Auditing location assignments between employees and locations.
-- Task:
-- 1. Find all location_ids that currently have employees assigned to them.
-- 2. Use EXCEPT to subtract these from all location_ids in the locations table.
-- 3. This reveals which corporate facilities currently have ZERO staff assigned!
-- ----------------------------------------------------------------------------

-- Write your solution below:
SELECT location_id FROM locations
EXCEPT
SELECT DISTINCT location_id FROM employees WHERE location_id IS NOT NULL;


-- ----------------------------------------------------------------------------
-- CHALLENGE 5: The Executive Regional Matrix (Session 2)
-- Scenario: The VP of Sales needs a quarterly revenue matrix from superstore.
-- Task:
-- 1. Group by region (handle NULL regions with COALESCE(region, 'Unknown')).
-- 2. Calculate total_orders (COUNT(*)) and total_sales (SUM(sales)).
-- 3. Pivot category sales into separate columns using CASE inside SUM:
--    - furniture_sales (sales where category = 'Furniture')
--    - office_sales (sales where category = 'Office Supplies')
--    - tech_sales (sales where category = 'Technology')
-- 4. Add tech_pct: The percentage of total sales generated by Technology.
-- 5. Order by total_sales descending.
-- ----------------------------------------------------------------------------

-- Write your solution below:
SELECT 
    COALESCE(region, 'Unknown') AS region,
    COUNT(*) AS total_orders,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(SUM(CASE WHEN category = 'Furniture' THEN sales ELSE 0 END), 2) AS furniture_sales,
    ROUND(SUM(CASE WHEN category = 'Office Supplies' THEN sales ELSE 0 END), 2) AS office_sales,
    ROUND(SUM(CASE WHEN category = 'Technology' THEN sales ELSE 0 END), 2) AS tech_sales,
    ROUND(
        100.0 * SUM(CASE WHEN category = 'Technology' THEN sales ELSE 0 END) / NULLIF(SUM(sales), 0),
        1
    ) AS tech_pct
FROM superstore
GROUP BY region
ORDER BY total_sales DESC;
